### ISSUE TITLE
one big js file vs multiple smaller js files?

### ISSUE THREAD

**Issue by miltoncandelero** [digitsensitive/phaser3-typescript#23]
Hi.
First of all, thank you for creating and maintaining this.
I am in the middle of a migration from Haxe/OpenFL and your boilerplate code has saved my life.

Now, I see that you generate a single bundle.js file where my previous framework (and the phaser pure js examples) use one file for phaser and another for the game.

is it better to have multiple smaller js files? or is it better one big blob?

Once again, thank you so much for your work!

**Comment by digitsensitive** [comment]
Hello @miltoncandelero! Thank you for your comment. I'm glad my repository was helpful.

I believe there are advantages and disadvantages to both approaches? Honestly, I haven't done enough with it yet and simply decided to generate only one file because it's easier to import it into the HTML file. I am open to discussions about it.

**Comment by digitsensitive** [comment]
I have thought about it again, and think that one file is currently better in the context of this repository. Closing this topic.
