### ISSUE TITLE
Building fails with phaser 3.16.1

### ISSUE THREAD

**Issue by CipSoft-Components** [digitsensitive/phaser3-typescript#29]
I tried to update to the current phaser version 3.16.1, but than everything breaks, because the games uses a removed API configuration.
Even if I only use the boilerplate as entry point, the project tries to build everything, and fails, because of the API problem.
Can you adjust the game examples? Is it possible, to configure the project in the way, that only a selected example, or the boilerplate, is build?

**Comment by digitsensitive** [comment]
Hello @CipSoft-Components 
Thank you for your feedback. The current version of the repository will fail with any newer version, because it is not compatible atm. I am working on the update to phaser version 3.16.2. However, the [following problem](https://github.com/photonstorm/phaser3-docs/issues/90) must be solved before I can perform an update.

**Comment by digitsensitive** [comment]
@CipSoft-Components I have finished the update to phaser version 3.16.2.

> Is it possible, to configure the project in the way, that only a selected example, or the boilerplate, is build?

Will take care of this later. Closing this issue.
